Update CSS design
colinschoen/enrollme pull request #34
Opened 2017-12-03 06:28 UTC by colinschoen

See screenshots below of new design...

<img width="1277" alt="screen shot 2017-12-02 at 22 27 23" src="https://user-images.githubusercontent.com/2927722/33522999-12f0b3f0-d7b0-11e7-8d86-468a5f3ef064.png">
<img width="1440" alt="screen shot 2017-12-02 at 22 27 11" src="https://user-images.githubusercontent.com/2927722/33523000-130a8dfc-d7b0-11e7-9b52-d927ea70a114.png">
<img width="1430" alt="screen shot 2017-12-02 at 22 27 04" src="https://user-images.githubusercontent.com/2927722/33523001-1320bd52-d7b0-11e7-94ab-4a15be451d0c.png">

Signed-off-by: Colin Schoen <cschoen2020@gmail.com>

2017-12-03 22:52 UTC, raychan3 requested changes
Did you take out "Name Visible to Other Teams"? Don't we still want it? In the original, we want the check box on that same line.
Also we wanted to take the red text.
Are we going by "Skill ids" or "Skills"?
Should we make those text boxes smaller?

2017-12-03 22:52 UTC, raychan3 commented
<img width="1002" alt="screen shot 2017-12-03 at 14 51 58" src="https://user-images.githubusercontent.com/13775834/33530782-9f337f80-d839-11e7-91f7-e47e9796d589.png">

2017-12-03 22:55 UTC, raychan3 commented
<img width="1002" alt="screen shot 2017-12-03 at 14 51 58" src="https://user-images.githubusercontent.com/13775834/33530831-0550582e-d83a-11e7-8387-98a66b441e46.png">

The check box I was talking about above.

2017-12-04 07:46 UTC, raychan3 approved these changes

2017-12-04 07:48 UTC, gabriel-gardner approved these changes

2017-12-04 07:52 UTC, merged